name: flutter_tutorial_2
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: "^0.4.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  sky_engine:
    path: ../engine/src/out/host_debug_unopt/gen/dart-pkg/sky_engine
  sky_services:
    path: ../engine/src/out/host_debug_unopt/gen/dart-pkg/sky_services

